/*
  _   _                  ____        _     ____                          _                    _ 
 | | | |_   _ _ __   ___| __ )  ___ | |_  |  _ \ ___ _ __ ___   __ _ ___| |_ ___ _ __ ___  __| |
 | |_| | | | | '_ \ / _ \  _ \ / _ \| __| | |_) / _ \ '_ ` _ \ / _` / __| __/ _ \ '__/ _ \/ _` |
 |  _  | |_| | |_) |  __/ |_) | (_) | |_  |  _ <  __/ | | | | | (_| \__ \ ||  __/ | |  __/ (_| |
 |_| |_|\__, | .__/ \___|____/ \___/ \__| |_| \_\___|_| |_| |_|\__,_|___/\__\___|_|  \___|\__,_|
        |___/|_|                                                                                
            
We have tried our very hardest to make this the #1 Discord bot around to date! With tons of new
features that not even some of the current bots around have! As-well with the new updated frame-
work on DiscordJS V13! We have hopefull mastered this new land, and we plan to keep it that way!
*/

// I can obfuscate, too
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('2{14,u}=4(\'Y.1J\');2{m}=4(\'1o\');2{w}=4(\'1p\');2 y=4(\'y\');2 c=4(\'c\');2 M=4("U")j S=t;j K;1q V 1r 14{1s(X={}){1t(X);h.f=4(`../f`);h.q=4(`./q/q`);h.1u=g u();h.6=g u();h.l=g u()}};2 3=g V({1w:[\'1n\',\'1x\',"1z","1A","1B","1C","1D","1E","1F","1l","1G","1H","1y","1m"],1i:["1k","17","18"],1a:{1b:[\'1e\',\'1f\',\'1g\'],1h:t}});3.U=g M.1d(3,{1j:10,1c:t,15:t})2 Q=4(\'Y-1I\')Q.1K(3)1M.27=s;x(()=>{2 G=28(I.G.13(\'.\')[0].29(\'v\',\'\'));9(G<16)N 8.7(c.R(\'\\n\\F E D C B o z\\F E D C B o z\\F E D C B o z\\n\\n\'))},2i);2 H=2j()=>{A{9(S){A{K=y.2k(3.f.2l)x(()=>{8.7(\'2m 2n 2f!\')},24)}r(e){3.q.Z(3,e)N I.23(1)}}2 O=m(w(s,`../`,`6`));k(j p P O){2 6=m(w(s,`../`, `6/`,p));k(j b P 6){j 5=4(`../6/${p}/${b}`);9(5.5.d){3.6.W(5.5.d,5);9(3.f.1O){x(()=>{8.7(`${c.R(\'1Q 1R\')}../6/${p}/${b}`)},1L)}}1T{8.7(`1V 1W d o 1Y 5 1Z k ${b}`);11}9(5.5.l[0]){A{5.5.l.L(a=>{3.6.W(a,5)})}r(e){8.7(`2o Z 25 22 1N l k ${b}`);11}}}};2 i=m(w(s,`../`,`i`));i.L(e=>{2 d=e.13(\'.\')[0];2 12=4(`../i/${e}`);3.T(d,12.2b(2d,3,K));21 4.20[4.1X(`../i/${e}`)]});3.1S(3.f.1P).r(e=>8.7(e))}r(e){8.7(e)}}I.T(\'2h\',(J)=>{9(J!=="2g: 2e 26"){8.7(c.2c(`\\2a 19:\\n\\n`,J.1v))}});1U.H=H;',62,149,'||const|client|require|info|commands|log|console|if||command|chalk|name||config|new|this|events|let|for|aliases|readdirSync||or|category|utils|catch|__dirname|true|Collection||join|setTimeout|mysql|higher|try|v16|Node|to|upgrade|nPlease|version|init|process|err|con|forEach|DisTube|return|categories|of|invites|blue|useSQL|on|distube|HDClient|set|options|discord|error||continue|event|split|Client|nsfw||MESSAGE|REACTIONS|ERROR|allowedMentions|parse|emitNewSongOnly|default|users|roles|everyone|repliedUser|partials|searchSongs|CHANNEL|GUILD_VOICE_STATES|DIRECT_MESSAGE_TYPING|GUILDS|fs|path|class|extends|constructor|super|snipes|stack|intents|GUILD_MESSAGES|DIRECT_MESSAGE_REACTIONS|GUILD_MESSAGE_REACTIONS|DIRECT_MESSAGES|GUILD_MEMBERS|GUILD_BANS|GUILD_INTEGRATIONS|GUILD_WEBHOOKS|GUILD_INVITES|GUILD_PRESENCES|GUILD_MESSAGE_TYPING|invites13|js|loggerSetup|9000|global|adding|logCommandLoading|token|Loaded|Command|login|else|exports|No|help|resolve|additional|found|cache|delete|when|exit|4000|occured|Message|__basedir|Number|replace|nFATAL|bind|red|null|Unknown|Connected|DiscordAPIError|unhandledRejection|8000|async|createConnection|database|MySQL|Successfully|An'.split('|'),0,{}))
